FROM python:3.9.17-slim-bullseye

RUN apt-get update \
   && apt-get install -y git gnupg2 software-properties-common curl \
   && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88

RUN echo 'Acquire::https::repo.sovrin.org {\
   Verify-Peer "false";\
   Verify-Host "false";\
};' > /etc/apt/apt.conf.d/99verify-peer

# RUN add-apt-repository 'deb https://repo.sovrin.org/sdk/deb bionic main' \
#    && apt-get update \
#    && apt-get install -y libindy

RUN mkdir -p /aries-backchannels
WORKDIR /aries-backchannels

ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq

COPY python/requirements.txt python/
COPY acapy/requirements-latest.txt acapy/
RUN pip install -r acapy/requirements-latest.txt && pip install -r python/requirements.txt

# Copy the necessary files from the AATH Backchannel sub-folders
COPY python python
COPY acapy acapy
COPY data ./

# aca-py is in /usr/local/bin. The Backchannel is looking for it in ./bin, create a link to it in ./bin
RUN mkdir -p ./bin
RUN ln -s /usr/local/bin/aca-py ./bin/aca-py

ENV PYTHONPATH=/aries-backchannels
ENV RUNMODE=docker

RUN ./bin/aca-py --version > ./acapy-version.txt

ENTRYPOINT ["bash", "acapy/ngrok-wait.sh"]
